#!/bin/csh

set PORT=9999

set FLAGS=''

cd ~/sw
sort lib/text/helpneeded -o lib/text/helpneeded -t : -k +1 -u

while (1)

  set DATE = (`date`);
  echo "autoscript starting game $DATE" >> syslog

# Echo to log, and mail to admin about game restarts. next 4 lines.
# Add in seperation and netstat information
  #echo "mailing admin game restart notification .."
  cd ~/sw/log
  #tail -n 30 syslog.6 > tail.txt &
  #netstat -m > nets.m
  #cat sep >> tail.txt
  #cat nets.m >> tail.txt
##
###  Removed this to make only 1 spam mail.
###  mail -s Restarts/GDB Output list4us@shadowwind.org < ~/shadowwind/log/tail.txt &
##
# Echo to log, and mail to admin about gdb outputs on restarts.
#cannot let this next line go to background mode... or it mail same thing 
#over and over.
  cd ~/sw
  #gdb bin/shadowwind lib/shadowwind.core < lib/command.lst > log/sw.gdb
  #cd ~/sw/log
  #cat sep2 >> sw.gdb
  #cat tail.txt >> sw.gdb
  #mail -s Restarts/GDB-Output list4us@shadowwind.org < ~/shadowwind/log/sw.gdb
  #rm sw.gdb
  #rm tail.txt
  #mv lib/shadowwind.core lib/shadowwind.core.1
  #mv lib/shadowwind.core.1 lib/shadowwind.core.2

# Change to base dir and start the mud.
  #cd ~/shadowwind
  bin/shadowwind $FLAGS $PORT >>& syslog
  #mv ~/shadowwind/shadowwind.core lib

#  fgrep "death trap" syslog >> log/dts
#  fgrep "Running" syslog >> log/restarts
#  fgrep "equipment lost" syslog >> log/rentgone
#  fgrep "usage" syslog >> log/usage

  fgrep ":A:" syslog >> log/levels
  fgrep ":G:" syslog >> log/godcmds
  fgrep ":K:" syslog >> log/rip
  fgrep ":L:" syslog >> log/loadlog
  fgrep ":P:" syslog >> log/badpws
  fgrep ":Q:" syslog >> log/quests
  fgrep ":W:" syslog >> log/delete
  fgrep ":X:" syslog >> log/cheatlog
  fgrep ":Y:" syslog >> log/pkpt

  fgrep "new player" syslog >> log/newplayers
  fgrep "SYSERR" syslog >> log/errors

  rm log/syslog.1
  mv log/syslog.2 log/syslog.1
  mv log/syslog.3 log/syslog.2
  mv log/syslog.4 log/syslog.3
  mv log/syslog.5 log/syslog.4
  mv log/syslog.6 log/syslog.5
  mv syslog       log/syslog.6
  touch syslog

  if (! -r .fastboot) then
    sleep 5
  else
    rm .fastboot
    sleep 5
  endif

  if (-e .killscript) then
    set DATE = (`date`);
    echo "autoscript killed $DATE"  >> syslog
    rm .killscript
    exit
  endif 

  while (-r pause) 
    sleep 60
  end

end


